<?php
/* 
 * Generated by CRUDigniter v2.0 Beta 
 * www.crudigniter.com
 */
 
class Categoria extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Categoria_model');
    } 

    /*
     * Listing of categorias
     */
    function index()
    {
        $data['categorias'] = $this->Categoria_model->get_all_categorias();
        $data['pagina'] = "Categorias";
        $data['sub_pagina'] = "Listar Categoria";
		
		if ($this->session->flashdata('msg')) {
            if ($this->session->flashdata('msg') == 'cadastrar') {
                $data['msg'] = '<div class="alert alert-success" role="alert"><b>'.$this->session->flashdata('nome').' </b>cadastrado com sucesso!</div>';
            }
            else{
                $data['msg'] = '<div class="alert alert-success" role="alert"><b>'.$this->session->flashdata('nome').' </b>atualizado com sucesso!</div>';   
            }
        }
		
        $this->load->view('header_view',$data);
        $this->load->view('categoria/index',$data);
        $this->load->view('footer_view',$data);
    }

    /*
     * Adding a new categoria
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('categorias_cod','Código','required|max_length[20]');
		$this->form_validation->set_rules('categorias_nome','Categoria','max_length[150]|required');
		$this->form_validation->set_rules('categorias_abre','Abreviatura','max_length[20]|required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'categorias_cod' => $this->input->post('categorias_cod'),
				'categorias_nome' => $this->input->post('categorias_nome'),
				'categorias_abre' => $this->input->post('categorias_abre'),
            );
            
            $categoria_id = $this->Categoria_model->add_categoria($params);
			
			$nome = $this->input->post('categorias_nome');
			$this->session->set_flashdata(array('msg' => 'cadastrar' , 'nome' => $nome));
			
            redirect('categoria/index');
        }
        else
        {
            $data['pagina'] = "Categorias";
            $data['sub_pagina'] = "Cadastrar Categoria";
            $this->load->view('header_view',$data);
            $this->load->view('categoria/add');
            $this->load->view('footer_view',$data);
        }
    }  

    /*
     * editaring a categoria
     */
    function editar($categorias_id)
    {   
        // check if the categoria exists before trying to editar it
        $categoria = $this->Categoria_model->get_categoria($categorias_id);
        
        if(isset($categoria['categorias_id']))
        {
            $this->load->library('form_validation');

		$this->form_validation->set_rules('categorias_cod','Código','required|max_length[20]');
		$this->form_validation->set_rules('categorias_nome','Categoria','max_length[150]|required');
		$this->form_validation->set_rules('categorias_abre','Abreviatura','max_length[20]|required');
		
		if($this->form_validation->run())     
            {   
                $params = array(
					'categorias_cod' => $this->input->post('categorias_cod'),
					'categorias_nome' => $this->input->post('categorias_nome'),
					'categorias_abre' => $this->input->post('categorias_abre'),
                );

                $this->Categoria_model->update_categoria($categorias_id,$params);
				
				$nome = $this->input->post('categorias_nome');
				$this->session->set_flashdata(array('msg' => 'atualizar' , 'nome' => $nome));
				
                redirect('categoria/index');
            }
            else
            {   
                $data['categoria'] = $this->Categoria_model->get_categoria($categorias_id);
    
                $data['pagina'] = "Categorias";
                $data['sub_pagina'] = "Editar Categoria";
                $this->load->view('header_view',$data);
                $this->load->view('categoria/editar',$data);
                $this->load->view('footer_view',$data);
            }
        }
        else
            show_error('The categoria you are trying to editar does not exist.');
    } 

    /*
     * Deleting categoria
     */
    function remove($categorias_id)
    {
        $categoria = $this->Categoria_model->get_categoria($categorias_id);

        // check if the categoria exists before trying to delete it
        if(isset($categoria['categorias_id']))
        {
            $this->Categoria_model->delete_categoria($categorias_id);
            redirect('categoria/index');
        }
        else
            show_error('The categoria you are trying to delete does not exist.');
    }
    
}
