<?php
/* 
 * Generated by CRUDigniter v2.0 Beta 
 * www.crudigniter.com
 */
 
class Cliente extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Cliente_model');
    } 

    /*
     * Listing of clientes
     */
    function index()
    {
        $data['clientes'] = $this->Cliente_model->get_all_clientes();
        $data['pagina'] = "Clientes";
        $data['sub_pagina'] = "Listar Clientes";
		
		if ($this->session->flashdata('msg')) {
            if ($this->session->flashdata('msg') == 'cadastrar') {
                $data['msg'] = '<div class="alert alert-success" role="alert"><b>'.$this->session->flashdata('nome').' </b>cadastrado com sucesso!</div>';
            }
            else{
                $data['msg'] = '<div class="alert alert-success" role="alert"><b>'.$this->session->flashdata('nome').' </b>atualizado com sucesso!</div>';   
            }
        }
		
        $this->load->view('header_view',$data);
        $this->load->view('cliente/index',$data);
        $this->load->view('footer_view',$data);
    }

    /*
     * Adding a new cliente
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('clientes_cod','Código','required|max_length[20]');
		$this->form_validation->set_rules('clientes_tipo','Tipo','required|integer');
		$this->form_validation->set_rules('clientes_cpf_cnpj','CPF/CNPJ','required|integer');
		$this->form_validation->set_rules('clientes_rg','RG','required|integer');
		$this->form_validation->set_rules('clientes_rg_orgao','RG Orgão','required');
		$this->form_validation->set_rules('clientes_rg_uf','RG UF','required');
		$this->form_validation->set_rules('clientes_rg_expedicao','RG Expedição','required');
		$this->form_validation->set_rules('clientes_nome','Nome','required|max_length[45]');
		$this->form_validation->set_rules('clientes_cnh','CNH','required|max_length[20]');
		$this->form_validation->set_rules('clientes_cod_despachente','Código Despachente','required|integer');
		$this->form_validation->set_rules('clientes_despachante','Despachante','required|max_length[45]');
		$this->form_validation->set_rules('clientes_cod_municipio','Código Município','max_length[20]');
		$this->form_validation->set_rules('clientes_municipio','Município','max_length[45]');
		$this->form_validation->set_rules('clientes_uf','UF','exact_length[2]');
		$this->form_validation->set_rules('clientes_endereco','Endereço','max_length[45]');
		$this->form_validation->set_rules('clientes_bairro','Bairro','max_length[45]');
		$this->form_validation->set_rules('clientes_complemento','Complemento','max_length[20]');
		$this->form_validation->set_rules('clientes_numero','Número','integer');
		$this->form_validation->set_rules('clientes_cep','CEP','integer|max_length[8]');
		$this->form_validation->set_rules('clientes_tipo_endereco','Tipo Endereço','max_length[20]');
		$this->form_validation->set_rules('clientes_telefone','Telefone','max_length[20]');
		$this->form_validation->set_rules('clientes_telefone_residencial','Telefone Residencial','max_length[20]');
		$this->form_validation->set_rules('clientes_celular','Celular','max_length[20]');
		$this->form_validation->set_rules('clientes_email','E-mail','max_length[40]|valid_email');
		$this->form_validation->set_rules('clientes_corres_cod_municipio','Código Município','max_length[20]');
		$this->form_validation->set_rules('clientes_corres_municipio','Município','max_length[150]');
		$this->form_validation->set_rules('clientes_corres_uf','UF','exact_length[2]');
		$this->form_validation->set_rules('clientes_corres_endereco','Endereço','max_length[60]');
		$this->form_validation->set_rules('clientes_corres_bairro','Bairro','max_length[60]');
		$this->form_validation->set_rules('clientes_corres_complemento','Complemento','max_length[40]');
		$this->form_validation->set_rules('clientes_corres_numero','Número','integer|max_length[11]');
		$this->form_validation->set_rules('clientes_corres_cep','CEP','integer|max_length[8]');
		$this->form_validation->set_rules('clientes_corres_tipo_endereco','Tipo Endereço','integer|max_length[11]');
		$this->form_validation->set_rules('clientes_corres_nome_tipo_endereco','Nome Tipo Endereço','max_length[40]');
		$this->form_validation->set_rules('clientes_adicionais_mae','Mãe','max_length[40]');
		$this->form_validation->set_rules('clientes_adicionais_pai','Pai','max_length[40]');
		$this->form_validation->set_rules('clientes_adicionais_estado_civil','Estado Civil','integer|max_length[2]');
		$this->form_validation->set_rules('clientes_adicionais_nascionalidade','Nascionalidade','max_length[40]');
		$this->form_validation->set_rules('clientes_adicionais_cod_municipio_natural','Código Município Naturalidade','max_length[20]');
		$this->form_validation->set_rules('clientes_adicionais_nome_municipio_naturalidade','Nome Município Naturalidade','max_length[40]');
		$this->form_validation->set_rules('clientes_adicionais_uf','UF','exact_length[2]');
		$this->form_validation->set_rules('clientes_adicionais_cep','CEP','integer|max_length[8]');
		$this->form_validation->set_rules('clientes_adicionais_sexo','Sexo','max_length[20]');
		$this->form_validation->set_rules('clientes_adicionais_cod_profissao','Código Profissão','max_length[20]');
		$this->form_validation->set_rules('clientes_adicionais_profissao','Profissão','max_length[40]');
		$this->form_validation->set_rules('clientes_adicionais_obs_resumida','Observação Resumida','max_length[150]');
		
		if($this->form_validation->run())     
        {   
			$clientes_numero = $this->input->post('clientes_numero');
			if($this->input->post('clientes_numero') == ""){
				$clientes_numero = NULL;
			}
			
			$clientes_cep = $this->input->post('clientes_cep');
			if($this->input->post('clientes_cep') == ""){
				$clientes_cep = NULL;
			}
			
			$clientes_corres_numero = $this->input->post('clientes_corres_numero');
			if($this->input->post('clientes_corres_numero') == ""){
				$clientes_corres_numero = NULL;
			}
			
			$clientes_corres_cep = $this->input->post('clientes_corres_cep');
			if($this->input->post('clientes_corres_cep') == ""){
				$clientes_corres_cep = NULL;
			}
			
			$clientes_corres_tipo_endereco = $this->input->post('clientes_corres_tipo_endereco');
			if($this->input->post('clientes_corres_tipo_endereco') == ""){
				$clientes_corres_tipo_endereco = NULL;
			}

			$clientes_adicionais_data_nascimento = $this->input->post('clientes_adicionais_data_nascimento');
			if($this->input->post('clientes_adicionais_data_nascimento') == ""){
				$clientes_adicionais_data_nascimento = NULL;
			}
			
			$clientes_adicionais_estado_civil = $this->input->post('clientes_adicionais_estado_civil');
			if($this->input->post('clientes_adicionais_estado_civil') == ""){
				$clientes_adicionais_estado_civil = NULL;
			}
			
			$clientes_adicionais_cep = $this->input->post('clientes_adicionais_cep');
			if($this->input->post('clientes_adicionais_cep') == ""){
				$clientes_adicionais_cep = NULL;
			}
			
            $params = array(
				'clientes_cod' => $this->input->post('clientes_cod'),
				'clientes_tipo' => $this->input->post('clientes_tipo'),
				'clientes_cpf_cnpj' => $this->input->post('clientes_cpf_cnpj'),
				'clientes_rg' => $this->input->post('clientes_rg'),
				'clientes_rg_orgao' => $this->input->post('clientes_rg_orgao'),
				'clientes_rg_uf' => $this->input->post('clientes_rg_uf'),
				'clientes_rg_expedicao' => $this->input->post('clientes_rg_expedicao'),
				'clientes_nome' => $this->input->post('clientes_nome'),
				'clientes_cnh' => $this->input->post('clientes_cnh'),
				'clientes_cod_despachente' => $this->input->post('clientes_cod_despachente'),
				'clientes_despachante' => $this->input->post('clientes_despachante'),
				'clientes_cod_municipio' => $this->input->post('clientes_cod_municipio'),
				'clientes_municipio' => $this->input->post('clientes_municipio'),
				'clientes_uf' => $this->input->post('clientes_uf'),
				'clientes_endereco' => $this->input->post('clientes_endereco'),
				'clientes_bairro' => $this->input->post('clientes_bairro'),
				'clientes_complemento' => $this->input->post('clientes_complemento'),
				'clientes_numero' => $clientes_numero,
				'clientes_cep' => $clientes_cep,
				'clientes_tipo_endereco' => $this->input->post('clientes_tipo_endereco'),
				'clientes_telefone' => $this->input->post('clientes_telefone'),
				'clientes_telefone_residencial' => $this->input->post('clientes_telefone_residencial'),
				'clientes_celular' => $this->input->post('clientes_celular'),
				'clientes_email' => $this->input->post('clientes_email'),
				'clientes_corres_cod_municipio' => $this->input->post('clientes_corres_cod_municipio'),
				'clientes_corres_municipio' => $this->input->post('clientes_corres_municipio'),
				'clientes_corres_uf' => $this->input->post('clientes_corres_uf'),
				'clientes_corres_endereco' => $this->input->post('clientes_corres_endereco'),
				'clientes_corres_bairro' => $this->input->post('clientes_corres_bairro'),
				'clientes_corres_complemento' => $this->input->post('clientes_corres_complemento'),
				'clientes_corres_numero' => $clientes_corres_numero,
				'clientes_corres_cep' => $clientes_corres_cep,
				'clientes_corres_tipo_endereco' => $clientes_corres_tipo_endereco,
				'clientes_corres_nome_tipo_endereco' => $this->input->post('clientes_corres_nome_tipo_endereco'),
				'clientes_adicionais_data_nascimento' => $clientes_adicionais_data_nascimento,
				'clientes_adicionais_mae' => $this->input->post('clientes_adicionais_mae'),
				'clientes_adicionais_pai' => $this->input->post('clientes_adicionais_pai'),
				'clientes_adicionais_estado_civil' => $clientes_adicionais_estado_civil,
				'clientes_adicionais_nascionalidade' => $this->input->post('clientes_adicionais_nascionalidade'),
				'clientes_adicionais_cod_municipio_natural' => $this->input->post('clientes_adicionais_cod_municipio_natural'),
				'clientes_adicionais_nome_municipio_naturalidade' => $this->input->post('clientes_adicionais_nome_municipio_naturalidade'),
				'clientes_adicionais_uf' => $this->input->post('clientes_adicionais_uf'),
				'clientes_adicionais_cep' => $clientes_adicionais_cep,
				'clientes_adicionais_sexo' => $this->input->post('clientes_adicionais_sexo'),
				'clientes_adicionais_cod_profissao' => $this->input->post('clientes_adicionais_cod_profissao'),
				'clientes_adicionais_profissao' => $this->input->post('clientes_adicionais_profissao'),
				'clientes_adicionais_obs_resumida' => $this->input->post('clientes_adicionais_obs_resumida'),
				'clientes_observacao_livre' => $this->input->post('clientes_observacao_livre'),
            );
            
            $cliente_id = $this->Cliente_model->add_cliente($params);
			
			$nome = $this->input->post('clientes_cod');
			$this->session->set_flashdata(array('msg' => 'cadastrar' , 'nome' => $nome));
			
            redirect('cliente/index');
        }
        else
        {
            $data['pagina'] = "Clientes";
            $data['sub_pagina'] = "Cadastrar Clientes";
            $this->load->view('header_view',$data);
            $this->load->view('cliente/add');
            $this->load->view('footer_view',$data);
        }
    }  

    /*
     * editaring a cliente
     */
    function editar($clientes_id)
    {   
        // check if the cliente exists before trying to editar it
        $cliente = $this->Cliente_model->get_cliente($clientes_id);
        
        if(isset($cliente['clientes_id']))
        {
            $this->load->library('form_validation');

		$this->form_validation->set_rules('clientes_cod','Código','required|max_length[20]');
		$this->form_validation->set_rules('clientes_tipo','Tipo','required|integer');
		$this->form_validation->set_rules('clientes_cpf_cnpj','CPF/CNPJ','required|integer');
		$this->form_validation->set_rules('clientes_rg','RG','required|integer');
		$this->form_validation->set_rules('clientes_rg_orgao','RG Orgão','required');
		$this->form_validation->set_rules('clientes_rg_uf','RG UF','required');
		$this->form_validation->set_rules('clientes_rg_expedicao','RG Expedição','required');
		$this->form_validation->set_rules('clientes_nome','Nome','required|max_length[45]');
		$this->form_validation->set_rules('clientes_cnh','CNH','required|max_length[20]');
		$this->form_validation->set_rules('clientes_cod_despachente','Código Despachente','required|integer');
		$this->form_validation->set_rules('clientes_despachante','Despachante','required|max_length[45]');
		$this->form_validation->set_rules('clientes_cod_municipio','Código Município','max_length[20]');
		$this->form_validation->set_rules('clientes_municipio','Município','max_length[45]');
		$this->form_validation->set_rules('clientes_uf','UF','exact_length[2]');
		$this->form_validation->set_rules('clientes_endereco','Endereço','max_length[45]');
		$this->form_validation->set_rules('clientes_bairro','Bairro','max_length[45]');
		$this->form_validation->set_rules('clientes_complemento','Complemento','max_length[20]');
		$this->form_validation->set_rules('clientes_numero','Número','integer');
		$this->form_validation->set_rules('clientes_cep','CEP','integer|max_length[8]');
		$this->form_validation->set_rules('clientes_tipo_endereco','Tipo Endereço','max_length[20]');
		$this->form_validation->set_rules('clientes_telefone','Telefone','max_length[20]');
		$this->form_validation->set_rules('clientes_telefone_residencial','Telefone Residencial','max_length[20]');
		$this->form_validation->set_rules('clientes_celular','Celular','max_length[20]');
		$this->form_validation->set_rules('clientes_email','E-mail','max_length[40]|valid_email');
		$this->form_validation->set_rules('clientes_corres_cod_municipio','Código Município','max_length[20]');
		$this->form_validation->set_rules('clientes_corres_municipio','Município','max_length[150]');
		$this->form_validation->set_rules('clientes_corres_uf','UF','exact_length[2]');
		$this->form_validation->set_rules('clientes_corres_endereco','Endereço','max_length[60]');
		$this->form_validation->set_rules('clientes_corres_bairro','Bairro','max_length[60]');
		$this->form_validation->set_rules('clientes_corres_complemento','Complemento','max_length[40]');
		$this->form_validation->set_rules('clientes_corres_numero','Número','integer|max_length[11]');
		$this->form_validation->set_rules('clientes_corres_cep','CEP','integer|max_length[8]');
		$this->form_validation->set_rules('clientes_corres_tipo_endereco','Tipo Endereço','integer|max_length[11]');
		$this->form_validation->set_rules('clientes_corres_nome_tipo_endereco','Nome Tipo Endereço','max_length[40]');
		$this->form_validation->set_rules('clientes_adicionais_mae','Mãe','max_length[40]');
		$this->form_validation->set_rules('clientes_adicionais_pai','Pai','max_length[40]');
		$this->form_validation->set_rules('clientes_adicionais_estado_civil','Estado Civil','integer|max_length[2]');
		$this->form_validation->set_rules('clientes_adicionais_nascionalidade','Nascionalidade','max_length[40]');
		$this->form_validation->set_rules('clientes_adicionais_cod_municipio_natural','Código Município Naturalidade','max_length[20]');
		$this->form_validation->set_rules('clientes_adicionais_nome_municipio_naturalidade','Nome Município Naturalidade','max_length[40]');
		$this->form_validation->set_rules('clientes_adicionais_uf','UF','exact_length[2]');
		$this->form_validation->set_rules('clientes_adicionais_cep','CEP','integer|max_length[8]');
		$this->form_validation->set_rules('clientes_adicionais_sexo','Sexo','max_length[20]');
		$this->form_validation->set_rules('clientes_adicionais_cod_profissao','Código Profissão','max_length[20]');
		$this->form_validation->set_rules('clientes_adicionais_profissao','Profissão','max_length[40]');
		$this->form_validation->set_rules('clientes_adicionais_obs_resumida','Observação Resumida','max_length[150]');
		
		if($this->form_validation->run())     
        {   
			$clientes_numero = $this->input->post('clientes_numero');
			if($this->input->post('clientes_numero') == ""){
				$clientes_numero = NULL;
			}
			
			$clientes_cep = $this->input->post('clientes_cep');
			if($this->input->post('clientes_cep') == ""){
				$clientes_cep = NULL;
			}
			
			$clientes_corres_numero = $this->input->post('clientes_corres_numero');
			if($this->input->post('clientes_corres_numero') == ""){
				$clientes_corres_numero = NULL;
			}
			
			$clientes_corres_cep = $this->input->post('clientes_corres_cep');
			if($this->input->post('clientes_corres_cep') == ""){
				$clientes_corres_cep = NULL;
			}
			
			$clientes_corres_tipo_endereco = $this->input->post('clientes_corres_tipo_endereco');
			if($this->input->post('clientes_corres_tipo_endereco') == ""){
				$clientes_corres_tipo_endereco = NULL;
			}

			$clientes_adicionais_data_nascimento = $this->input->post('clientes_adicionais_data_nascimento');
			if($this->input->post('clientes_adicionais_data_nascimento') == ""){
				$clientes_adicionais_data_nascimento = NULL;
			}
			
			$clientes_adicionais_estado_civil = $this->input->post('clientes_adicionais_estado_civil');
			if($this->input->post('clientes_adicionais_estado_civil') == ""){
				$clientes_adicionais_estado_civil = NULL;
			}
			
			$clientes_adicionais_cep = $this->input->post('clientes_adicionais_cep');
			if($this->input->post('clientes_adicionais_cep') == ""){
				$clientes_adicionais_cep = NULL;
			}
			
            $params = array(
				'clientes_cod' => $this->input->post('clientes_cod'),
				'clientes_tipo' => $this->input->post('clientes_tipo'),
				'clientes_cpf_cnpj' => $this->input->post('clientes_cpf_cnpj'),
				'clientes_rg' => $this->input->post('clientes_rg'),
				'clientes_rg_orgao' => $this->input->post('clientes_rg_orgao'),
				'clientes_rg_uf' => $this->input->post('clientes_rg_uf'),
				'clientes_rg_expedicao' => $this->input->post('clientes_rg_expedicao'),
				'clientes_nome' => $this->input->post('clientes_nome'),
				'clientes_cnh' => $this->input->post('clientes_cnh'),
				'clientes_cod_despachente' => $this->input->post('clientes_cod_despachente'),
				'clientes_despachante' => $this->input->post('clientes_despachante'),
				'clientes_cod_municipio' => $this->input->post('clientes_cod_municipio'),
				'clientes_municipio' => $this->input->post('clientes_municipio'),
				'clientes_uf' => $this->input->post('clientes_uf'),
				'clientes_endereco' => $this->input->post('clientes_endereco'),
				'clientes_bairro' => $this->input->post('clientes_bairro'),
				'clientes_complemento' => $this->input->post('clientes_complemento'),
				'clientes_numero' => $clientes_numero,
				'clientes_cep' => $clientes_cep,
				'clientes_tipo_endereco' => $this->input->post('clientes_tipo_endereco'),
				'clientes_telefone' => $this->input->post('clientes_telefone'),
				'clientes_telefone_residencial' => $this->input->post('clientes_telefone_residencial'),
				'clientes_celular' => $this->input->post('clientes_celular'),
				'clientes_email' => $this->input->post('clientes_email'),
				'clientes_corres_cod_municipio' => $this->input->post('clientes_corres_cod_municipio'),
				'clientes_corres_municipio' => $this->input->post('clientes_corres_municipio'),
				'clientes_corres_uf' => $this->input->post('clientes_corres_uf'),
				'clientes_corres_endereco' => $this->input->post('clientes_corres_endereco'),
				'clientes_corres_bairro' => $this->input->post('clientes_corres_bairro'),
				'clientes_corres_complemento' => $this->input->post('clientes_corres_complemento'),
				'clientes_corres_numero' => $clientes_corres_numero,
				'clientes_corres_cep' => $clientes_corres_cep,
				'clientes_corres_tipo_endereco' => $clientes_corres_tipo_endereco,
				'clientes_corres_nome_tipo_endereco' => $this->input->post('clientes_corres_nome_tipo_endereco'),
				'clientes_adicionais_data_nascimento' => $clientes_adicionais_data_nascimento,
				'clientes_adicionais_mae' => $this->input->post('clientes_adicionais_mae'),
				'clientes_adicionais_pai' => $this->input->post('clientes_adicionais_pai'),
				'clientes_adicionais_estado_civil' => $clientes_adicionais_estado_civil,
				'clientes_adicionais_nascionalidade' => $this->input->post('clientes_adicionais_nascionalidade'),
				'clientes_adicionais_cod_municipio_natural' => $this->input->post('clientes_adicionais_cod_municipio_natural'),
				'clientes_adicionais_nome_municipio_naturalidade' => $this->input->post('clientes_adicionais_nome_municipio_naturalidade'),
				'clientes_adicionais_uf' => $this->input->post('clientes_adicionais_uf'),
				'clientes_adicionais_cep' => $clientes_adicionais_cep,
				'clientes_adicionais_sexo' => $this->input->post('clientes_adicionais_sexo'),
				'clientes_adicionais_cod_profissao' => $this->input->post('clientes_adicionais_cod_profissao'),
				'clientes_adicionais_profissao' => $this->input->post('clientes_adicionais_profissao'),
				'clientes_adicionais_obs_resumida' => $this->input->post('clientes_adicionais_obs_resumida'),
				'clientes_observacao_livre' => $this->input->post('clientes_observacao_livre'),
            );

                $this->Cliente_model->update_cliente($clientes_id,$params);

				$nome = $this->input->post('clientes_cod');
				$this->session->set_flashdata(array('msg' => 'atualizar' , 'nome' => $nome));
				
                redirect('cliente/index');
            }
            else
            {   
                $data['cliente'] = $this->Cliente_model->get_cliente($clientes_id);
    
                $data['pagina'] = "Clientes";
                $data['sub_pagina'] = "Editar Clientes";
                $this->load->view('header_view',$data);
                $this->load->view('cliente/editar',$data);
                $this->load->view('footer_view',$data);
            }
        }
        else
            show_error('The cliente you are trying to editar does not exist.');
    } 

    /*
     * Deleting cliente
     */
    function remove($clientes_id)
    {
        $cliente = $this->Cliente_model->get_cliente($clientes_id);

        // check if the cliente exists before trying to delete it
        if(isset($cliente['clientes_id']))
        {
            $this->Cliente_model->delete_cliente($clientes_id);
            redirect('cliente/index');
        }
        else
            show_error('The cliente you are trying to delete does not exist.');
    }
    
}
