<?php
/* 
 * Generated by CRUDigniter v2.0 Beta 
 * www.crudigniter.com
 */
 
class Cor extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Cor_model');
    } 

    /*
     * Listing of cores
     */
    function index()
    {
        $data['cores'] = $this->Cor_model->get_all_cores();
        $data['pagina'] = "Cores";
        $data['sub_pagina'] = "Lista Cores";
		
		if ($this->session->flashdata('msg')) {
            if ($this->session->flashdata('msg') == 'cadastrar') {
                $data['msg'] = '<div class="alert alert-success" role="alert"><b>'.$this->session->flashdata('nome').' </b>cadastrado com sucesso!</div>';
            }
            else{
                $data['msg'] = '<div class="alert alert-success" role="alert"><b>'.$this->session->flashdata('nome').' </b>atualizado com sucesso!</div>';   
            }
        }
		
        $this->load->view('header_view',$data);
        $this->load->view('cor/index',$data);
        $this->load->view('footer_view',$data);
    }

    /*
     * Adding a new core
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('cores_cod','Código','required|max_length[20]');
		$this->form_validation->set_rules('cores_nome','Cor','required|max_length[150]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'cores_cod' => $this->input->post('cores_cod'),
				'cores_nome' => $this->input->post('cores_nome'),
            );
            
            $cor_id = $this->Cor_model->add_cor($params);
			
			$nome = $this->input->post('cores_nome');
			$this->session->set_flashdata(array('msg' => 'cadastrar' , 'nome' => $nome));
			
            redirect('cor/index');
        }
        else
        {
            $data['pagina'] = "Cores";
            $data['sub_pagina'] = "Cadastrar Cor";
            $this->load->view('header_view',$data);
            $this->load->view('cor/add');
            $this->load->view('footer_view',$data);
        }
    }  

    /*
     * editaring a core
     */
    function editar($cores_id)
    {   
        // check if the core exists before trying to editar it
        $cor = $this->Cor_model->get_cor($cores_id);
        
        if(isset($cor['cores_id']))
        {
            $this->load->library('form_validation');

		$this->form_validation->set_rules('cores_cod','Código','required|max_length[20]');
		$this->form_validation->set_rules('cores_nome','Cor','required|max_length[150]');
		
		if($this->form_validation->run())     
            {   
                $params = array(
					'cores_cod' => $this->input->post('cores_cod'),
					'cores_nome' => $this->input->post('cores_nome'),
                );

                $this->Cor_model->update_cor($cores_id,$params);  

				$nome = $this->input->post('cores_nome');
				$this->session->set_flashdata(array('msg' => 'atualizar' , 'nome' => $nome));
				
                redirect('cor/index');
            }
            else
            {   
                $data['cor'] = $this->Cor_model->get_cor($cores_id);
    
                $data['pagina'] = "Cores";
                $data['sub_pagina'] = "Editar Cor";
                $this->load->view('header_view',$data);
                $this->load->view('cor/editar',$data);
                $this->load->view('footer_view',$data);
            }
        }
        else
            show_error('The core you are trying to editar does not exist.');
    } 

    /*
     * Deleting core
     */
    function remove($cores_id)
    {
        $cor = $this->Cor_model->get_cor($cores_id);

        // check if the core exists before trying to delete it
        if(isset($cor['cores_id']))
        {
            $this->Cor_model->delete_cor($cores_id);
            redirect('cor/index');
        }
        else
            show_error('The core you are trying to delete does not exist.');
    }
    
}
