<?php
/* 
 * Generated by CRUDigniter v2.0 Beta 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
    } 

    /*
     * Listing of carrocerias
     */
    function index()
    {
		
        $data['pagina'] = "Dashboard";
        $data['sub_pagina'] = "Dashboard";
		
        $this->load->view('header_view',$data);
        $this->load->view('dashboard/index');
        $this->load->view('footer_view',$data);
    }
}

?>
