<?php
/* 
 * Generated by CRUDigniter v2.0 Beta 
 * www.crudigniter.com
 */
 
class Despachante extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Despachante_model');
    } 

    /*
     * Listing of despachantes
     */
    function index()
    {
        $data['despachantes'] = $this->Despachante_model->get_all_despachantes();
        $data['pagina'] = "Despachantes";
        $data['sub_pagina'] = "Listar Despachantes";
		
		if ($this->session->flashdata('msg')) {
            if ($this->session->flashdata('msg') == 'cadastrar') {
                $data['msg'] = '<div class="alert alert-success" role="alert"><b>'.$this->session->flashdata('nome').' </b>cadastrado com sucesso!</div>';
            }
            else{
                $data['msg'] = '<div class="alert alert-success" role="alert"><b>'.$this->session->flashdata('nome').' </b>atualizado com sucesso!</div>';   
            }
        }
		
        $this->load->view('header_view',$data);
        $this->load->view('despachante/index',$data);
        $this->load->view('footer_view',$data);
    }

    /*
     * Adding a new despachante
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('desp_nome','Nome','required|max_length[40]');
		$this->form_validation->set_rules('desp_credencial','Credencial','required|max_length[40]');
		$this->form_validation->set_rules('desp_cpf_cnpj','CPF/CNPJ','required|integer|max_length[14]');
		$this->form_validation->set_rules('desp_cidade','Cidade','required|integer|max_length[6]');
		$this->form_validation->set_rules('desp_endereco','Endereço','required|max_length[150]');
		$this->form_validation->set_rules('desp_bairro','Bairro','required|max_length[40]');
		$this->form_validation->set_rules('desp_complemento','Complemento','required|max_length[255]');
		$this->form_validation->set_rules('desp_cep','CEP','required|integer|max_length[8]');
		$this->form_validation->set_rules('desp_numero','Número','required|integer|max_length[9]');
		$this->form_validation->set_rules('desp_email','E-mail','required|valid_email|max_length[40]');
		$this->form_validation->set_rules('desp_celular','Celular','required|max_length[20]');
		$this->form_validation->set_rules('desp_telefone','Telefone','required|max_length[20]');
		$this->form_validation->set_rules('desp_estado_civil','Estado Civil','required|integer|max_length[2]');
		$this->form_validation->set_rules('desp_rg','RG','required|integer|max_length[10]');
		$this->form_validation->set_rules('desp_rg_uf','RG UF','required|exact_length[2]');
		$this->form_validation->set_rules('desp_rg_orgao','RG Orgão','required|max_length[10]');
		$this->form_validation->set_rules('desp_detran','Detran','required|max_length[50]');
		$this->form_validation->set_rules('desp_logotipo','Logotipo','required|max_length[60]');
		$this->form_validation->set_rules('desp_data_incricao','Data Inscrição','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'desp_nome' => $this->input->post('desp_nome'),
				'desp_credencial' => $this->input->post('desp_credencial'),
				'desp_cpf_cnpj' => $this->input->post('desp_cpf_cnpj'),
				'desp_cidade' => $this->input->post('desp_cidade'),
				'desp_endereco' => $this->input->post('desp_endereco'),
				'desp_bairro' => $this->input->post('desp_bairro'),
				'desp_complemento' => $this->input->post('desp_complemento'),
				'desp_cep' => $this->input->post('desp_cep'),
				'desp_numero' => $this->input->post('desp_numero'),
				'desp_email' => $this->input->post('desp_email'),
				'desp_celular' => $this->input->post('desp_celular'),
				'desp_telefone' => $this->input->post('desp_telefone'),
				'desp_estado_civil' => $this->input->post('desp_estado_civil'),
				'desp_rg' => $this->input->post('desp_rg'),
				'desp_rg_uf' => $this->input->post('desp_rg_uf'),
				'desp_rg_orgao' => $this->input->post('desp_rg_orgao'),
				'desp_detran' => $this->input->post('desp_detran'),
				'desp_logotipo' => $this->input->post('desp_logotipo'),
				'desp_data_incricao' => $this->input->post('desp_data_incricao'),
            );
            
            $despachante_id = $this->Despachante_model->add_despachante($params);
			
			$nome = $this->input->post('desp_nome');
			$this->session->set_flashdata(array('msg' => 'cadastrar' , 'nome' => $nome));
			
            redirect('despachante/index');
        }
        else
        {
            $data['pagina'] = "Despachantes";
            $data['sub_pagina'] = "Cadastrar Despachantes";
            $this->load->view('header_view',$data);
            $this->load->view('despachante/add');
            $this->load->view('footer_view',$data);
        }
    }  

    /*
     * editaring a despachante
     */
    function editar($desp_id)
    {   
        // check if the despachante exists before trying to editar it
        $despachante = $this->Despachante_model->get_despachante($desp_id);
        
        if(isset($despachante['desp_id']))
        {
            $this->load->library('form_validation');

		$this->form_validation->set_rules('desp_nome','Nome','required|max_length[40]');
		$this->form_validation->set_rules('desp_credencial','Credencial','required|max_length[40]');
		$this->form_validation->set_rules('desp_cpf_cnpj','CPF/CNPJ','required|integer|max_length[14]');
		$this->form_validation->set_rules('desp_cidade','Cidade','required|integer|max_length[6]');
		$this->form_validation->set_rules('desp_endereco','Endereço','required|max_length[150]');
		$this->form_validation->set_rules('desp_bairro','Bairro','required|max_length[40]');
		$this->form_validation->set_rules('desp_complemento','Complemento','required|max_length[255]');
		$this->form_validation->set_rules('desp_cep','CEP','required|integer|max_length[8]');
		$this->form_validation->set_rules('desp_numero','Número','required|integer|max_length[9]');
		$this->form_validation->set_rules('desp_email','E-mail','required|valid_email|max_length[40]');
		$this->form_validation->set_rules('desp_celular','Celular','required|max_length[20]');
		$this->form_validation->set_rules('desp_telefone','Telefone','required|max_length[20]');
		$this->form_validation->set_rules('desp_estado_civil','Estado Civil','required|integer|max_length[2]');
		$this->form_validation->set_rules('desp_rg','RG','required|integer|max_length[10]');
		$this->form_validation->set_rules('desp_rg_uf','RG UF','required|exact_length[2]');
		$this->form_validation->set_rules('desp_rg_orgao','RG Orgão','required|max_length[10]');
		$this->form_validation->set_rules('desp_detran','Detran','required|max_length[50]');
		$this->form_validation->set_rules('desp_logotipo','Logotipo','required|max_length[60]');
		$this->form_validation->set_rules('desp_data_incricao','Data Inscrição','required');
		
		if($this->form_validation->run())     
            {   
                $params = array(
					'desp_nome' => $this->input->post('desp_nome'),
					'desp_credencial' => $this->input->post('desp_credencial'),
					'desp_cpf_cnpj' => $this->input->post('desp_cpf_cnpj'),
					'desp_cidade' => $this->input->post('desp_cidade'),
					'desp_endereco' => $this->input->post('desp_endereco'),
					'desp_bairro' => $this->input->post('desp_bairro'),
					'desp_complemento' => $this->input->post('desp_complemento'),
					'desp_cep' => $this->input->post('desp_cep'),
					'desp_numero' => $this->input->post('desp_numero'),
					'desp_email' => $this->input->post('desp_email'),
					'desp_celular' => $this->input->post('desp_celular'),
					'desp_telefone' => $this->input->post('desp_telefone'),
					'desp_estado_civil' => $this->input->post('desp_estado_civil'),
					'desp_rg' => $this->input->post('desp_rg'),
					'desp_rg_uf' => $this->input->post('desp_rg_uf'),
					'desp_rg_orgao' => $this->input->post('desp_rg_orgao'),
					'desp_detran' => $this->input->post('desp_detran'),
					'desp_logotipo' => $this->input->post('desp_logotipo'),
					'desp_data_incricao' => $this->input->post('desp_data_incricao'),
                );

                $this->Despachante_model->update_despachante($desp_id,$params);

				$nome = $this->input->post('desp_nome');
				$this->session->set_flashdata(array('msg' => 'atualizar' , 'nome' => $nome));
				
                redirect('despachante/index');
            }
            else
            {   
                $data['despachante'] = $this->Despachante_model->get_despachante($desp_id);
    
                $data['pagina'] = "Despachantes";
                $data['sub_pagina'] = "Editar Despachantes";
                $this->load->view('header_view',$data);
                $this->load->view('despachante/editar',$data);
                $this->load->view('footer_view',$data);
            }
        }
        else
            show_error('The despachante you are trying to editar does not exist.');
    } 

    /*
     * Deleting despachante
     */
    function remove($desp_id)
    {
        $despachante = $this->Despachante_model->get_despachante($desp_id);

        // check if the despachante exists before trying to delete it
        if(isset($despachante['desp_id']))
        {
            $this->Despachante_model->delete_despachante($desp_id);
            redirect('despachante/index');
        }
        else
            show_error('The despachante you are trying to delete does not exist.');
    }
    
}
