<?php
/* 
 * Generated by CRUDigniter v2.0 Beta 
 * www.crudigniter.com
 */
 
class Especie extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Especie_model');
    } 

    /*
     * Listing of especies
     */
    function index()
    {
        $data['especies'] = $this->Especie_model->get_all_especies();
        $data['pagina'] = "Espécies";
        $data['sub_pagina'] = "Lista Espécies";
		
		if ($this->session->flashdata('msg')) {
            if ($this->session->flashdata('msg') == 'cadastrar') {
                $data['msg'] = '<div class="alert alert-success" role="alert"><b>'.$this->session->flashdata('nome').' </b>cadastrado com sucesso!</div>';
            }
            else{
                $data['msg'] = '<div class="alert alert-success" role="alert"><b>'.$this->session->flashdata('nome').' </b>atualizado com sucesso!</div>';   
            }
        }
		
        $this->load->view('header_view',$data);
        $this->load->view('especie/index',$data);
        $this->load->view('footer_view',$data);
    }

    /*
     * Adding a new especie
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('especies_cod','Código','required|max_length[20]');
		$this->form_validation->set_rules('especies_nome','Espécie','required|max_length[150]');
		$this->form_validation->set_rules('especies_abrev','Abreviatura','required|max_length[20]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'especies_cod' => $this->input->post('especies_cod'),
				'especies_nome' => $this->input->post('especies_nome'),
				'especies_abrev' => $this->input->post('especies_abrev'),
            );
            
            $especie_id = $this->Especie_model->add_especie($params);
			
			$nome = $this->input->post('especies_nome');
			$this->session->set_flashdata(array('msg' => 'cadastrar' , 'nome' => $nome));
			
            redirect('especie/index');
        }
        else
        {
            $data['pagina'] = "Espécies";
            $data['sub_pagina'] = "Cadastrar Espécie";
            $this->load->view('header_view',$data);
            $this->load->view('especie/add');
            $this->load->view('footer_view',$data);
        }
    }  

    /*
     * editaring a especie
     */
    function editar($especies_id)
    {   
        // check if the especie exists before trying to editar it
        $especie = $this->Especie_model->get_especie($especies_id);
        
        if(isset($especie['especies_id']))
        {
            $this->load->library('form_validation');

		$this->form_validation->set_rules('especies_cod','Código','required|max_length[20]');
		$this->form_validation->set_rules('especies_nome','Espécie','required|max_length[150]');
		$this->form_validation->set_rules('especies_abrev','Abreviatura','required|max_length[20]');
		
		if($this->form_validation->run())     
            {   
                $params = array(
					'especies_cod' => $this->input->post('especies_cod'),
					'especies_nome' => $this->input->post('especies_nome'),
					'especies_abrev' => $this->input->post('especies_abrev'),
                );

                $this->Especie_model->update_especie($especies_id,$params);

				$nome = $this->input->post('especies_nome');
				$this->session->set_flashdata(array('msg' => 'atualizar' , 'nome' => $nome));
				
                redirect('especie/index');
            }
            else
            {   
                $data['especie'] = $this->Especie_model->get_especie($especies_id);
    
                $data['pagina'] = "Espécies";
                $data['sub_pagina'] = "Editar Espécie";
                $this->load->view('header_view',$data);
                $this->load->view('especie/editar',$data);
                $this->load->view('footer_view',$data);
            }
        }
        else
            show_error('The especie you are trying to editar does not exist.');
    } 

    /*
     * Deleting especie
     */
    function remove($especies_id)
    {
        $especie = $this->Especie_model->get_especie($especies_id);

        // check if the especie exists before trying to delete it
        if(isset($especie['especies_id']))
        {
            $this->Especie_model->delete_especie($especies_id);
            redirect('especie/index');
        }
        else
            show_error('The especie you are trying to delete does not exist.');
    }
    
}
