<?php
/* 
 * Generated by CRUDigniter v2.0 Beta 
 * www.crudigniter.com
 */
 
class Marcas_modelo extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Marcas_modelo_model');
    } 

    /*
     * Listing of marcas_modelos
     */
    function index()
    {
        $data['marcas_modelos'] = $this->Marcas_modelo_model->get_all_marcas_modelos();
        $data['pagina'] = "Marca / Modelo";
        $data['sub_pagina'] = "Listar Marca / Modelo";
		
		if ($this->session->flashdata('msg')) {
            if ($this->session->flashdata('msg') == 'cadastrar') {
                $data['msg'] = '<div class="alert alert-success" role="alert"><b>'.$this->session->flashdata('nome').' </b>cadastrado com sucesso!</div>';
            }
            else{
                $data['msg'] = '<div class="alert alert-success" role="alert"><b>'.$this->session->flashdata('nome').' </b>atualizado com sucesso!</div>';   
            }
        }		
		
        $this->load->view('header_view',$data);
        $this->load->view('marcas_modelo/index',$data);
        $this->load->view('footer_view',$data);
    }

    /*
     * Adding a new marcas_modelo
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('marcas_modelos_cod','Código','required|max_length[20]');
		$this->form_validation->set_rules('marcas_modelos_nome','Marca / Modelo','required|max_length[150]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'marcas_modelos_cod' => $this->input->post('marcas_modelos_cod'),
				'marcas_modelos_nome' => $this->input->post('marcas_modelos_nome'),
            );
            
            $marcas_modelo_id = $this->Marcas_modelo_model->add_marcas_modelo($params);
			
			$nome = $this->input->post('marcas_modelos_nome');
			$this->session->set_flashdata(array('msg' => 'cadastrar' , 'nome' => $nome));			
			
            redirect('marcas_modelo/index');
        }
        else
        {
            $data['pagina'] = "Marca / Modelo";
            $data['sub_pagina'] = "Cadastrar Marca / Modelo";
            $this->load->view('header_view',$data);
            $this->load->view('marcas_modelo/add');
            $this->load->view('footer_view',$data);
        }
    }  

    /*
     * editaring a marcas_modelo
     */
    function editar($marcas_modelos_id)
    {   
        // check if the marcas_modelo exists before trying to editar it
        $marcas_modelo = $this->Marcas_modelo_model->get_marcas_modelo($marcas_modelos_id);
        
        if(isset($marcas_modelo['marcas_modelos_id']))
        {
            $this->load->library('form_validation');

		$this->form_validation->set_rules('marcas_modelos_cod','Código','required|max_length[20]');
		$this->form_validation->set_rules('marcas_modelos_nome','Marca / Modelo','required|max_length[150]');
		
		if($this->form_validation->run())     
            {   
                $params = array(
					'marcas_modelos_cod' => $this->input->post('marcas_modelos_cod'),
					'marcas_modelos_nome' => $this->input->post('marcas_modelos_nome'),
                );

                $this->Marcas_modelo_model->update_marcas_modelo($marcas_modelos_id,$params);

				$nome = $this->input->post('marcas_modelos_nome');
				$this->session->set_flashdata(array('msg' => 'atualizar' , 'nome' => $nome));
				
                redirect('marcas_modelo/index');
            }
            else
            {   
                $data['marcas_modelo'] = $this->Marcas_modelo_model->get_marcas_modelo($marcas_modelos_id);
    
                $data['pagina'] = "Marca / Modelo";
                $data['sub_pagina'] = "Editar Marca / Modelo";
                $this->load->view('header_view',$data);
                $this->load->view('marcas_modelo/editar',$data);
                $this->load->view('footer_view',$data);
            }
        }
        else
            show_error('The marcas_modelo you are trying to editar does not exist.');
    } 

    /*
     * Deleting marcas_modelo
     */
    function remove($marcas_modelos_id)
    {
        $marcas_modelo = $this->Marcas_modelo_model->get_marcas_modelo($marcas_modelos_id);

        // check if the marcas_modelo exists before trying to delete it
        if(isset($marcas_modelo['marcas_modelos_id']))
        {
            $this->Marcas_modelo_model->delete_marcas_modelo($marcas_modelos_id);
            redirect('marcas_modelo/index');
        }
        else
            show_error('The marcas_modelo you are trying to delete does not exist.');
    }
    
}
