<?php
/* 
 * Generated by CRUDigniter v2.0 Beta 
 * www.crudigniter.com
 */
 
class Restricao extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Restricao_model');
    } 

    /*
     * Listing of restricoes
     */
    function index()
    {
        $data['restricoes'] = $this->Restricao_model->get_all_restricoes();
        $data['pagina'] = "Restrição";
        $data['sub_pagina'] = "Listar Restrição";
		
		if ($this->session->flashdata('msg')) {
            if ($this->session->flashdata('msg') == 'cadastrar') {
                $data['msg'] = '<div class="alert alert-success" role="alert"><b>'.$this->session->flashdata('nome').' </b>cadastrado com sucesso!</div>';
            }
            else{
                $data['msg'] = '<div class="alert alert-success" role="alert"><b>'.$this->session->flashdata('nome').' </b>atualizado com sucesso!</div>';   
            }
        }		
		
        $this->load->view('header_view',$data);
        $this->load->view('restricao/index',$data);
        $this->load->view('footer_view',$data);
    }

    /*
     * Adding a new restrico
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('restricoes_cod','Código','required|max_length[20]');
		$this->form_validation->set_rules('restricoes_nome','Restrição','required|max_length[150]');
		$this->form_validation->set_rules('restricoes_abrev','Abreviatura','required|max_length[20]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'restricoes_cod' => $this->input->post('restricoes_cod'),
				'restricoes_nome' => $this->input->post('restricoes_nome'),
				'restricoes_abrev' => $this->input->post('restricoes_abrev'),
            );
            
            $restricao_id = $this->Restricao_model->add_restricao($params);
			
			$nome = $this->input->post('restricoes_nome');
			$this->session->set_flashdata(array('msg' => 'cadastrar' , 'nome' => $nome));
			
            redirect('restricao/index');
        }
        else
        {
            $data['pagina'] = "Restrição";
            $data['sub_pagina'] = "Cadastrar Restrição";
            $this->load->view('header_view',$data);
            $this->load->view('restricao/add');
            $this->load->view('footer_view',$data);
        }
    }  

    /*
     * editaring a restrico
     */
    function editar($restricoes_id)
    {   
        // check if the restrico exists before trying to editar it
        $restricao = $this->Restricao_model->get_restricao($restricoes_id);
        
        if(isset($restricao['restricoes_id']))
        {
            $this->load->library('form_validation');

		$this->form_validation->set_rules('restricoes_cod','Código','required|max_length[20]');
		$this->form_validation->set_rules('restricoes_nome','Restrição','required|max_length[150]');
		$this->form_validation->set_rules('restricoes_abrev','Abreviatura','required|max_length[20]');
		
		if($this->form_validation->run())     
            {   
                $params = array(
					'restricoes_cod' => $this->input->post('restricoes_cod'),
					'restricoes_nome' => $this->input->post('restricoes_nome'),
					'restricoes_abrev' => $this->input->post('restricoes_abrev'),
                );

                $this->Restricao_model->update_restricao($restricoes_id,$params);

				$nome = $this->input->post('restricoes_nome');
				$this->session->set_flashdata(array('msg' => 'atualizar' , 'nome' => $nome));
				
                redirect('restricao/index');
            }
            else
            {   
                $data['restricao'] = $this->Restricao_model->get_restricao($restricoes_id);
    
                $data['pagina'] = "Restrição";
                $data['sub_pagina'] = "Editar Restrição";
                $this->load->view('header_view',$data);
                $this->load->view('restricao/editar',$data);
                $this->load->view('footer_view',$data);
            }
        }
        else
            show_error('The restrico you are trying to editar does not exist.');
    } 

    /*
     * Deleting restrico
     */
    function remove($restricoes_id)
    {
        $restricao = $this->Restricao_model->get_restricao($restricoes_id);

        // check if the restrico exists before trying to delete it
        if(isset($restricao['restricoes_id']))
        {
            $this->Restricao_model->delete_restricao($restricoes_id);
            redirect('restricao/index');
        }
        else
            show_error('The restrico you are trying to delete does not exist.');
    }
    
}
