<?php
/* 
 * Generated by CRUDigniter v2.0 Beta 
 * www.crudigniter.com
 */
 
class Tipo_veiculo extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tipo_veiculo_model');
    } 

    /*
     * Listing of tipo_veiculos
     */
    function index()
    {
        $data['tipo_veiculos'] = $this->Tipo_veiculo_model->get_all_tipo_veiculos();
        
        $data['pagina'] = "Tipo de Veículo";
        $data['sub_pagina'] = "Listar Tipo de Veículo";
		
		if ($this->session->flashdata('msg')) {
            if ($this->session->flashdata('msg') == 'cadastrar') {
                $data['msg'] = '<div class="alert alert-success" role="alert"><b>'.$this->session->flashdata('nome').' </b>cadastrado com sucesso!</div>';
            }
            else{
                $data['msg'] = '<div class="alert alert-success" role="alert"><b>'.$this->session->flashdata('nome').' </b>atualizado com sucesso!</div>';   
            }
        }		
		
        $this->load->view('header_view',$data);
        $this->load->view('tipo_veiculo/index',$data);
        $this->load->view('footer_view',$data);
    }

    /*
     * Adding a new tipo_veiculo
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('tipo_veiculos_cod','Código','required|max_length[20]');
		$this->form_validation->set_rules('tipo_veiculos_nome','Tipo Veículo','required|max_length[150]');
		$this->form_validation->set_rules('tipo_veiculos_abrev','Abreviatura','required|max_length[20]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'tipo_veiculos_cod' => $this->input->post('tipo_veiculos_cod'),
				'tipo_veiculos_nome' => $this->input->post('tipo_veiculos_nome'),
				'tipo_veiculos_abrev' => $this->input->post('tipo_veiculos_abrev'),
            );
            
            $tipo_veiculo_id = $this->Tipo_veiculo_model->add_tipo_veiculo($params);
			
			$nome = $this->input->post('tipo_veiculos_nome');
			$this->session->set_flashdata(array('msg' => 'cadastrar' , 'nome' => $nome));			
			
            redirect('tipo_veiculo/index');
        }
        else
        {
            $data['pagina'] = "Tipo de Veículo";
            $data['sub_pagina'] = "Cadastrar Tipo de Veículo";
            $this->load->view('header_view',$data);
            $this->load->view('tipo_veiculo/add');
            $this->load->view('footer_view',$data);
        }
    }  

    /*
     * editaring a tipo_veiculo
     */
    function editar($tipo_veiculos_id)
    {   
        // check if the tipo_veiculo exists before trying to editar it
        $tipo_veiculo = $this->Tipo_veiculo_model->get_tipo_veiculo($tipo_veiculos_id);
        
        if(isset($tipo_veiculo['tipo_veiculos_id']))
        {
            $this->load->library('form_validation');

		$this->form_validation->set_rules('tipo_veiculos_cod','Código','required|max_length[20]');
		$this->form_validation->set_rules('tipo_veiculos_nome','Tipo Veículo','required|max_length[150]');
		$this->form_validation->set_rules('tipo_veiculos_abrev','Abreviatura','required|max_length[20]');
		
		if($this->form_validation->run())     
            {   
                $params = array(
					'tipo_veiculos_cod' => $this->input->post('tipo_veiculos_cod'),
					'tipo_veiculos_nome' => $this->input->post('tipo_veiculos_nome'),
					'tipo_veiculos_abrev' => $this->input->post('tipo_veiculos_abrev'),
                );

                $this->Tipo_veiculo_model->update_tipo_veiculo($tipo_veiculos_id,$params);

				$nome = $this->input->post('tipo_veiculos_nome');
				$this->session->set_flashdata(array('msg' => 'atualizar' , 'nome' => $nome));
				
                redirect('tipo_veiculo/index');
            }
            else
            {   
                $data['tipo_veiculo'] = $this->Tipo_veiculo_model->get_tipo_veiculo($tipo_veiculos_id);
    
                $data['pagina'] = "Tipo de Veículo";
                $data['sub_pagina'] = "Editar Tipo de Veículo";
                $this->load->view('header_view',$data);
                $this->load->view('tipo_veiculo/editar',$data);
                $this->load->view('footer_view',$data);
            }
        }
        else
            show_error('The tipo_veiculo you are trying to editar does not exist.');
    } 

    /*
     * Deleting tipo_veiculo
     */
    function remove($tipo_veiculos_id)
    {
        $tipo_veiculo = $this->Tipo_veiculo_model->get_tipo_veiculo($tipo_veiculos_id);

        // check if the tipo_veiculo exists before trying to delete it
        if(isset($tipo_veiculo['tipo_veiculos_id']))
        {
            $this->Tipo_veiculo_model->delete_tipo_veiculo($tipo_veiculos_id);
            redirect('tipo_veiculo/index');
        }
        else
            show_error('The tipo_veiculo you are trying to delete does not exist.');
    }
    
}
