<?php
/* 
 * Generated by CRUDigniter v2.0 Beta 
 * www.crudigniter.com
 */
 
class Veiculo extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Veiculo_model');
    } 

    /*
     * Listing of veiculos
     */
    function index()
    {
        $data['veiculos'] = $this->Veiculo_model->get_all_veiculos();
        $data['pagina'] = "Veículos";
        $data['sub_pagina'] = "Listar Veículos";
		
		if ($this->session->flashdata('msg')) {
            if ($this->session->flashdata('msg') == 'cadastrar') {
                $data['msg'] = '<div class="alert alert-success" role="alert"><b>'.$this->session->flashdata('nome').' </b>cadastrado com sucesso!</div>';
            }
            else{
                $data['msg'] = '<div class="alert alert-success" role="alert"><b>'.$this->session->flashdata('nome').' </b>atualizado com sucesso!</div>';   
            }
        }
		
        $this->load->view('header_view',$data);
        $this->load->view('veiculo/index',$data);
        $this->load->view('footer_view',$data);
    }

    /*
     * Adding a new veiculo
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('veic_codigo','Código','required|max_length[10]');
		$this->form_validation->set_rules('veic_placa_uf','Placa/UF','required|exact_length[2]');
		$this->form_validation->set_rules('veic_final_placa','Final da Placa','required|exact_length[1]|integer');
		$this->form_validation->set_rules('veic_marca_modelo','Marca/Modelo','required|max_length[40]');
		$this->form_validation->set_rules('veic_chassi','Chassi','required|max_length[40]');
		$this->form_validation->set_rules('veic_renavam','Renavam','required|max_length[40]');
		$this->form_validation->set_rules('veic_cpf_cnpj_prop','CPF/CNPJ Proprietário','required|max_length[16]');
		$this->form_validation->set_rules('veic_procedencia','Procedência','required|max_length[40]');
		$this->form_validation->set_rules('veic_data_cad','Data Cadastro','required');
		$this->form_validation->set_rules('veic_remarcado','Remarcado','max_length[1]|integer');
		$this->form_validation->set_rules('veic_alongado','Alongado','max_length[1]|integer');
		$this->form_validation->set_rules('veic_fabricacao','Fabricação','max_length[40]');
		$this->form_validation->set_rules('veic_categoria','Categoria','max_length[2]|integer');
		
		$this->form_validation->set_rules('veic_tipo','Tipo','max_length[2]|integer');
		$this->form_validation->set_rules('veic_cor','Cor','max_length[2]|integer');
		$this->form_validation->set_rules('veic_ano_fabric','Ano de Fabricação','exact_length[4]|integer');
		$this->form_validation->set_rules('veic_ano_mod','Ano Modelo','exact_length[4]|integer');
		$this->form_validation->set_rules('veic_lugares','Lugares','max_length[40]');
		$this->form_validation->set_rules('veic_especie','Especie','integer|max_length[2]');
		$this->form_validation->set_rules('veic_combustivel','Combustível','max_length[2]|integer');
		$this->form_validation->set_rules('veic_potencia','Potência','max_length[40]');
		$this->form_validation->set_rules('veic_cmt','CMT','max_length[40]');
		$this->form_validation->set_rules('veic_cilindrada','Cilindrada','max_length[10]');
		$this->form_validation->set_rules('veic_carga','Carga','max_length[40]');
		$this->form_validation->set_rules('veic_rtb','RTB','max_length[40]');
		$this->form_validation->set_rules('veic_num_eixos','Número de Eixos','max_length[2]|integer');
		$this->form_validation->set_rules('veic_pbt','PBT','max_length[40]');
		$this->form_validation->set_rules('veic_num_carroc','Número Carroceria','max_length[40]');
		$this->form_validation->set_rules('veic_tipo_carroc','Tipo Carroceria','max_length[40]');
		$this->form_validation->set_rules('veic_num_motor','Número Motor','max_length[40]');
		$this->form_validation->set_rules('veic_km','KM','integer|max_length[6]');
		$this->form_validation->set_rules('veic_arrend_merc','Arrendamento Mercantil','integer|max_length[1]');
		$this->form_validation->set_rules('veic_restricao','Restricão','max_length[40]');
		$this->form_validation->set_rules('veic_prop_ant','Proprietário Anterior','max_length[40]');
		$this->form_validation->set_rules('veic_cpf_cnpj','CPF/CNPJ','max_length[16]');
		$this->form_validation->set_rules('veic_placa_uf_ant','Placa/UF Anterior','exact_length[2]');
		$this->form_validation->set_rules('veic_crv_ant','CRV Anterior','max_length[40]');
		$this->form_validation->set_rules('veic_cod_munic','Código Município','integer|max_length[6]');
		$this->form_validation->set_rules('veic_munic','Município','max_length[40]');
		$this->form_validation->set_rules('veic_uf','UF','max_length[40]');
		$this->form_validation->set_rules('veic_nota_cnpj','CNPJ','integer|max_length[14]');
		$this->form_validation->set_rules('veic_nota_uf','Nota UF','exact_length[2]');
		$this->form_validation->set_rules('veic_nota_numero_nota','Número da Nota Fiscal','integer|max_length[14]');
		$this->form_validation->set_rules('veic_nota_envelope','Envelope','max_length[20]');
		$this->form_validation->set_rules('veic_nota_serie','Série','max_length[20]');
		$this->form_validation->set_rules('veic_nota_crv','CRV','max_length[20]');
		$this->form_validation->set_rules('veic_nota_urt','URT','max_length[60]');
		$this->form_validation->set_rules('veic_nota_insc_estadual','Inscrição Estadual','integer|max_length[14]');
		$this->form_validation->set_rules('veic_nota_valor','Valor','decimal');
		$this->form_validation->set_rules('veic_adicionais_obs_resumida','Observação Resumida','max_length[250]');
		$this->form_validation->set_rules('veic_adicionais_exigencia','Exigência','max_length[250]');
		$this->form_validation->set_rules('veic_adicionais_acessorios_adicionais','Acessórios Adicionais','max_length[250]');
		$this->form_validation->set_rules('veic_adicionais_nome_usuario','Nome de Usuário','max_length[40]');
		$this->form_validation->set_rules('veic_adicionais_email','E-mail','max_length[40]');
		$this->form_validation->set_rules('veic_adicionais_ddd','DDD','max_length[4]');
		$this->form_validation->set_rules('veic_adicionais_usuario_telefone','Telefone Usuário','max_length[20]');
		$this->form_validation->set_rules('veic_condutor_nome_condutor','Nome Condutor','max_length[40]');
		$this->form_validation->set_rules('veic_condutor_tel_1','Telefone 1','max_length[20]');
		$this->form_validation->set_rules('veic_condutor_tel_2','Telefone 2','max_length[20]');
		$this->form_validation->set_rules('veic_condutor_email','E-mail','max_length[40]');
		
		if($this->form_validation->run())     
        {   
            
			$veic_remarcado = $this->input->post('veic_remarcado');
			if($this->input->post('veic_remarcado') == ""){
				$veic_remarcado = NULL;
			}
			
			$veic_alongado = $this->input->post('veic_alongado');
			if($this->input->post('veic_alongado') == ""){
				$veic_alongado = NULL;
			}
			
			$veic_categoria = $this->input->post('veic_categoria');
			if($this->input->post('veic_categoria') == ""){
				$veic_categoria = NULL;
			}
			
			$veic_data_aquis = $this->input->post('veic_data_aquis');
			if($this->input->post('veic_data_aquis') == ""){
				$veic_data_aquis = NULL;
			}
			
			$veic_tipo = $this->input->post('veic_tipo');
			if($this->input->post('veic_tipo') == ""){
				$veic_tipo = NULL;				
			}
			
			$veic_cor = $this->input->post('veic_cor');
			if($this->input->post('veic_cor') == ""){
				$veic_cor = NULL;
			}
			
			$veic_ano_fabric = $this->input->post('veic_ano_fabric');
			if($this->input->post('veic_ano_fabric') == ""){
				$veic_ano_fabric = NULL;
			}
			
			$veic_ano_mod = $this->input->post('veic_ano_mod');
			if($this->input->post('veic_ano_mod') == ""){
				$veic_ano_mod = NULL;
			}
			
			$veic_especie = $this->input->post('veic_especie');
			if($this->input->post('veic_especie') == ""){
				$veic_especie = NULL;
			}
			
			$veic_combustivel = $this->input->post('veic_combustivel');
			if($this->input->post('veic_combustivel') == ""){
				$veic_combustivel = NULL;
			}
			
			$veic_num_eixos = $this->input->post('veic_num_eixos');
			if($this->input->post('veic_num_eixos') == ""){
				$veic_num_eixos = NULL;
			}
			
			$veic_km = $this->input->post('veic_km');
			if($this->input->post('veic_km') == ""){
				$veic_km = NULL;
			}
			
			$veic_arrend_merc = $this->input->post('veic_arrend_merc');
			if($this->input->post('veic_arrend_merc') == ""){
				$veic_arrend_merc = NULL;
			}
			
			$veic_cod_munic = $this->input->post('veic_cod_munic');
			if($this->input->post('veic_cod_munic') == ""){
				$veic_cod_munic = NULL;
			}
			
			$veic_nota_cnpj = $this->input->post('veic_nota_cnpj');
			if($this->input->post('veic_nota_cnpj') == ""){
				$veic_nota_cnpj = NULL;
			}
			
			$veic_nota_numero_nota = $this->input->post('veic_nota_numero_nota');
			if($this->input->post('veic_nota_numero_nota') == ""){
				$veic_nota_numero_nota = NULL;
			}
			
			$veic_nota_insc_estadual = $this->input->post('veic_nota_insc_estadual');
			if($this->input->post('veic_nota_insc_estadual') == ""){
				$veic_nota_insc_estadual = NULL;
			}
			
			$veic_nota_data = $this->input->post('veic_nota_data');
			if($this->input->post('veic_nota_data') == ""){
				$veic_nota_data = NULL;
			}
			
			$veic_nota_valor = $this->input->post('veic_nota_valor');
			if($this->input->post('veic_nota_valor') == ""){
				$veic_nota_valor = NULL;
			}
			
			$params = array(
				'veic_codigo' => $this->input->post('veic_codigo'),
				'veic_placa_uf' => $this->input->post('veic_placa_uf'),
				'veic_final_placa' => $this->input->post('veic_final_placa'),
				'veic_marca_modelo' => $this->input->post('veic_marca_modelo'),
				'veic_chassi' => $this->input->post('veic_chassi'),
				'veic_renavam' => $this->input->post('veic_renavam'),
				'veic_cpf_cnpj_prop' => $this->input->post('veic_cpf_cnpj_prop'),
				'veic_procedencia' => $this->input->post('veic_procedencia'),
				'veic_data_cad' => $this->input->post('veic_data_cad'),
				'veic_remarcado' => $veic_remarcado,
				'veic_alongado' => $veic_alongado,
				'veic_fabricacao' => $this->input->post('veic_fabricacao'),
				'veic_categoria' => $veic_categoria,
				'veic_data_aquis' => $veic_data_aquis,
				'veic_tipo' => $veic_tipo,
				'veic_cor' => $veic_cor,
				'veic_ano_fabric' => $veic_ano_fabric,
				'veic_ano_mod' => $veic_ano_mod,
				'veic_lugares' => $this->input->post('veic_lugares'),
				'veic_especie' => $veic_especie,
				'veic_combustivel' => $veic_combustivel,
				'veic_potencia' => $this->input->post('veic_potencia'),
				'veic_cmt' => $this->input->post('veic_cmt'),
				'veic_cilindrada' => $this->input->post('veic_cilindrada'),
				'veic_carga' => $this->input->post('veic_carga'),
				'veic_rtb' => $this->input->post('veic_rtb'),
				'veic_num_eixos' => $veic_num_eixos,
				'veic_pbt' => $this->input->post('veic_pbt'),
				'veic_num_carroc' => $this->input->post('veic_num_carroc'),
				'veic_tipo_carroc' => $this->input->post('veic_tipo_carroc'),
				'veic_num_motor' => $this->input->post('veic_num_motor'),
				'veic_km' => $veic_km,
				'veic_arrend_merc' => $veic_arrend_merc,
				'veic_restricao' => $this->input->post('veic_restricao'),
				'veic_prop_ant' => $this->input->post('veic_prop_ant'),
				'veic_cpf_cnpj' => $this->input->post('veic_cpf_cnpj'),
				'veic_placa_uf_ant' => $this->input->post('veic_placa_uf_ant'),
				'veic_crv_ant' => $this->input->post('veic_crv_ant'),
				'veic_cod_munic' => $veic_cod_munic,
				'veic_munic' => $this->input->post('veic_munic'),
				'veic_uf' => $this->input->post('veic_uf'),
				'veic_nota_cnpj' => $veic_nota_cnpj,
				'veic_nota_uf' => $this->input->post('veic_nota_uf'),
				'veic_nota_numero_nota' => $veic_nota_numero_nota,
				'veic_nota_envelope' => $this->input->post('veic_nota_envelope'),
				'veic_nota_serie' => $this->input->post('veic_nota_serie'),
				'veic_nota_crv' => $this->input->post('veic_nota_crv'),
				'veic_nota_urt' => $this->input->post('veic_nota_urt'),
				'veic_nota_insc_estadual' => $veic_nota_insc_estadual,
				'veic_nota_data' => $veic_nota_data,
				'veic_nota_valor' => $veic_nota_valor,
				'veic_adicionais_obs_resumida' => $this->input->post('veic_adicionais_obs_resumida'),
				'veic_adicionais_exigencia' => $this->input->post('veic_adicionais_exigencia'),
				'veic_adicionais_acessorios_adicionais' => $this->input->post('veic_adicionais_acessorios_adicionais'),
				'veic_adicionais_nome_usuario' => $this->input->post('veic_adicionais_nome_usuario'),
				'veic_adicionais_email' => $this->input->post('veic_adicionais_email'),
				'veic_adicionais_ddd' => $this->input->post('veic_adicionais_ddd'),
				'veic_adicionais_usuario_telefone' => $this->input->post('veic_adicionais_usuario_telefone'),
				'veic_condutor_nome_condutor' => $this->input->post('veic_condutor_nome_condutor'),
				'veic_condutor_tel_1' => $this->input->post('veic_condutor_tel_1'),
				'veic_condutor_tel_2' => $this->input->post('veic_condutor_tel_2'),
				'veic_condutor_email' => $this->input->post('veic_condutor_email'),
				'veic_obs_livre' => $this->input->post('veic_obs_livre'),
            );
            
            $veiculo_id = $this->Veiculo_model->add_veiculo($params);
			
			$nome = $this->input->post('veic_codigo');
			$this->session->set_flashdata(array('msg' => 'cadastrar' , 'nome' => $nome));
			
            redirect('veiculo/index');
        }
        else
        {
            $data['pagina'] = "Veículos";
            $data['sub_pagina'] = "Cadastrar Veículos";
            $this->load->view('header_view',$data);
            $this->load->view('veiculo/add');
            $this->load->view('footer_view',$data);
        }
    }  

    /*
     * editaring a veiculo
     */
    function editar($veic_id)
    {   
        // check if the veiculo exists before trying to editar it
        $veiculo = $this->Veiculo_model->get_veiculo($veic_id);
        
        if(isset($veiculo['veic_id']))
        {
            $this->load->library('form_validation');

		$this->form_validation->set_rules('veic_codigo','Código','required|max_length[10]');
		$this->form_validation->set_rules('veic_placa_uf','Placa/UF','required|exact_length[2]');
		$this->form_validation->set_rules('veic_final_placa','Final da Placa','required|exact_length[1]|integer');
		$this->form_validation->set_rules('veic_marca_modelo','Marca/Modelo','required|max_length[40]');
		$this->form_validation->set_rules('veic_chassi','Chassi','required|max_length[40]');
		$this->form_validation->set_rules('veic_renavam','Renavam','required|max_length[40]');
		$this->form_validation->set_rules('veic_cpf_cnpj_prop','CPF/CNPJ Proprietário','required|max_length[16]');
		$this->form_validation->set_rules('veic_procedencia','Procedência','required|max_length[40]');
		$this->form_validation->set_rules('veic_data_cad','Data Cadastro','required');
		$this->form_validation->set_rules('veic_remarcado','Remarcado','max_length[1]|integer');
		$this->form_validation->set_rules('veic_alongado','Alongado','max_length[1]|integer');
		$this->form_validation->set_rules('veic_fabricacao','Fabricação','max_length[40]');
		$this->form_validation->set_rules('veic_categoria','Categoria','max_length[2]|integer');
		
		$this->form_validation->set_rules('veic_tipo','Tipo','max_length[2]|integer');
		$this->form_validation->set_rules('veic_cor','Cor','max_length[2]|integer');
		$this->form_validation->set_rules('veic_ano_fabric','Ano de Fabricação','exact_length[4]|integer');
		$this->form_validation->set_rules('veic_ano_mod','Ano Modelo','exact_length[4]|integer');
		$this->form_validation->set_rules('veic_lugares','Lugares','max_length[40]');
		$this->form_validation->set_rules('veic_especie','Especie','integer|max_length[2]');
		$this->form_validation->set_rules('veic_combustivel','Combustível','max_length[2]|integer');
		$this->form_validation->set_rules('veic_potencia','Potência','max_length[40]');
		$this->form_validation->set_rules('veic_cmt','CMT','max_length[40]');
		$this->form_validation->set_rules('veic_cilindrada','Cilindrada','max_length[10]');
		$this->form_validation->set_rules('veic_carga','Carga','max_length[40]');
		$this->form_validation->set_rules('veic_rtb','RTB','max_length[40]');
		$this->form_validation->set_rules('veic_num_eixos','Número de Eixos','max_length[2]|integer');
		$this->form_validation->set_rules('veic_pbt','PBT','max_length[40]');
		$this->form_validation->set_rules('veic_num_carroc','Número Carroceria','max_length[40]');
		$this->form_validation->set_rules('veic_tipo_carroc','Tipo Carroceria','max_length[40]');
		$this->form_validation->set_rules('veic_num_motor','Número Motor','max_length[40]');
		$this->form_validation->set_rules('veic_km','KM','integer|max_length[6]');
		$this->form_validation->set_rules('veic_arrend_merc','Arrendamento Mercantil','integer|max_length[1]');
		$this->form_validation->set_rules('veic_restricao','Restricão','max_length[40]');
		$this->form_validation->set_rules('veic_prop_ant','Proprietário Anterior','max_length[40]');
		$this->form_validation->set_rules('veic_cpf_cnpj','CPF/CNPJ','max_length[16]');
		$this->form_validation->set_rules('veic_placa_uf_ant','Placa/UF Anterior','exact_length[2]');
		$this->form_validation->set_rules('veic_crv_ant','CRV Anterior','max_length[40]');
		$this->form_validation->set_rules('veic_cod_munic','Código Município','integer|max_length[6]');
		$this->form_validation->set_rules('veic_munic','Município','max_length[40]');
		$this->form_validation->set_rules('veic_uf','UF','max_length[40]');
		$this->form_validation->set_rules('veic_nota_cnpj','CNPJ','integer|max_length[14]');
		$this->form_validation->set_rules('veic_nota_uf','Nota UF','exact_length[2]');
		$this->form_validation->set_rules('veic_nota_numero_nota','Número da Nota Fiscal','integer|max_length[14]');
		$this->form_validation->set_rules('veic_nota_envelope','Envelope','max_length[20]');
		$this->form_validation->set_rules('veic_nota_serie','Série','max_length[20]');
		$this->form_validation->set_rules('veic_nota_crv','CRV','max_length[20]');
		$this->form_validation->set_rules('veic_nota_urt','URT','max_length[60]');
		$this->form_validation->set_rules('veic_nota_insc_estadual','Inscrição Estadual','integer|max_length[14]');
		$this->form_validation->set_rules('veic_nota_valor','Valor','decimal');
		$this->form_validation->set_rules('veic_adicionais_obs_resumida','Observação Resumida','max_length[250]');
		$this->form_validation->set_rules('veic_adicionais_exigencia','Exigência','max_length[250]');
		$this->form_validation->set_rules('veic_adicionais_acessorios_adicionais','Acessórios Adicionais','max_length[250]');
		$this->form_validation->set_rules('veic_adicionais_nome_usuario','Nome de Usuário','max_length[40]');
		$this->form_validation->set_rules('veic_adicionais_email','E-mail','max_length[40]');
		$this->form_validation->set_rules('veic_adicionais_ddd','DDD','max_length[4]');
		$this->form_validation->set_rules('veic_adicionais_usuario_telefone','Telefone Usuário','max_length[20]');
		$this->form_validation->set_rules('veic_condutor_nome_condutor','Nome Condutor','max_length[40]');
		$this->form_validation->set_rules('veic_condutor_tel_1','Telefone 1','max_length[20]');
		$this->form_validation->set_rules('veic_condutor_tel_2','Telefone 2','max_length[20]');
		$this->form_validation->set_rules('veic_condutor_email','E-mail','max_length[40]');
		
		if($this->form_validation->run())     
            {   
                $veic_remarcado = $this->input->post('veic_remarcado');
			if($this->input->post('veic_remarcado') == ""){
				$veic_remarcado = NULL;
			}
			
			$veic_alongado = $this->input->post('veic_alongado');
			if($this->input->post('veic_alongado') == ""){
				$veic_alongado = NULL;
			}
			
			$veic_categoria = $this->input->post('veic_categoria');
			if($this->input->post('veic_categoria') == ""){
				$veic_categoria = NULL;
			}
			
			$veic_data_aquis = $this->input->post('veic_data_aquis');
			if($this->input->post('veic_data_aquis') == ""){
				$veic_data_aquis = NULL;
			}
			
			$veic_tipo = $this->input->post('veic_tipo');
			if($this->input->post('veic_tipo') == ""){
				$veic_tipo = NULL;				
			}
			
			$veic_cor = $this->input->post('veic_cor');
			if($this->input->post('veic_cor') == ""){
				$veic_cor = NULL;
			}
			
			$veic_ano_fabric = $this->input->post('veic_ano_fabric');
			if($this->input->post('veic_ano_fabric') == ""){
				$veic_ano_fabric = NULL;
			}
			
			$veic_ano_mod = $this->input->post('veic_ano_mod');
			if($this->input->post('veic_ano_mod') == ""){
				$veic_ano_mod = NULL;
			}
			
			$veic_especie = $this->input->post('veic_especie');
			if($this->input->post('veic_especie') == ""){
				$veic_especie = NULL;
			}
			
			$veic_combustivel = $this->input->post('veic_combustivel');
			if($this->input->post('veic_combustivel') == ""){
				$veic_combustivel = NULL;
			}
			
			$veic_num_eixos = $this->input->post('veic_num_eixos');
			if($this->input->post('veic_num_eixos') == ""){
				$veic_num_eixos = NULL;
			}
			
			$veic_km = $this->input->post('veic_km');
			if($this->input->post('veic_km') == ""){
				$veic_km = NULL;
			}
			
			$veic_arrend_merc = $this->input->post('veic_arrend_merc');
			if($this->input->post('veic_arrend_merc') == ""){
				$veic_arrend_merc = NULL;
			}
			
			$veic_cod_munic = $this->input->post('veic_cod_munic');
			if($this->input->post('veic_cod_munic') == ""){
				$veic_cod_munic = NULL;
			}
			
			$veic_nota_cnpj = $this->input->post('veic_nota_cnpj');
			if($this->input->post('veic_nota_cnpj') == ""){
				$veic_nota_cnpj = NULL;
			}
			
			$veic_nota_numero_nota = $this->input->post('veic_nota_numero_nota');
			if($this->input->post('veic_nota_numero_nota') == ""){
				$veic_nota_numero_nota = NULL;
			}
			
			$veic_nota_insc_estadual = $this->input->post('veic_nota_insc_estadual');
			if($this->input->post('veic_nota_insc_estadual') == ""){
				$veic_nota_insc_estadual = NULL;
			}
			
			$veic_nota_data = $this->input->post('veic_nota_data');
			if($this->input->post('veic_nota_data') == ""){
				$veic_nota_data = NULL;
			}
			
			$veic_nota_valor = $this->input->post('veic_nota_valor');
			if($this->input->post('veic_nota_valor') == ""){
				$veic_nota_valor = NULL;
			}
			
			$params = array(
				'veic_codigo' => $this->input->post('veic_codigo'),
				'veic_placa_uf' => $this->input->post('veic_placa_uf'),
				'veic_final_placa' => $this->input->post('veic_final_placa'),
				'veic_marca_modelo' => $this->input->post('veic_marca_modelo'),
				'veic_chassi' => $this->input->post('veic_chassi'),
				'veic_renavam' => $this->input->post('veic_renavam'),
				'veic_cpf_cnpj_prop' => $this->input->post('veic_cpf_cnpj_prop'),
				'veic_procedencia' => $this->input->post('veic_procedencia'),
				'veic_data_cad' => $this->input->post('veic_data_cad'),
				'veic_remarcado' => $veic_remarcado,
				'veic_alongado' => $veic_alongado,
				'veic_fabricacao' => $this->input->post('veic_fabricacao'),
				'veic_categoria' => $veic_categoria,
				'veic_data_aquis' => $veic_data_aquis,
				'veic_tipo' => $veic_tipo,
				'veic_cor' => $veic_cor,
				'veic_ano_fabric' => $veic_ano_fabric,
				'veic_ano_mod' => $veic_ano_mod,
				'veic_lugares' => $this->input->post('veic_lugares'),
				'veic_especie' => $veic_especie,
				'veic_combustivel' => $veic_combustivel,
				'veic_potencia' => $this->input->post('veic_potencia'),
				'veic_cmt' => $this->input->post('veic_cmt'),
				'veic_cilindrada' => $this->input->post('veic_cilindrada'),
				'veic_carga' => $this->input->post('veic_carga'),
				'veic_rtb' => $this->input->post('veic_rtb'),
				'veic_num_eixos' => $veic_num_eixos,
				'veic_pbt' => $this->input->post('veic_pbt'),
				'veic_num_carroc' => $this->input->post('veic_num_carroc'),
				'veic_tipo_carroc' => $this->input->post('veic_tipo_carroc'),
				'veic_num_motor' => $this->input->post('veic_num_motor'),
				'veic_km' => $veic_km,
				'veic_arrend_merc' => $veic_arrend_merc,
				'veic_restricao' => $this->input->post('veic_restricao'),
				'veic_prop_ant' => $this->input->post('veic_prop_ant'),
				'veic_cpf_cnpj' => $this->input->post('veic_cpf_cnpj'),
				'veic_placa_uf_ant' => $this->input->post('veic_placa_uf_ant'),
				'veic_crv_ant' => $this->input->post('veic_crv_ant'),
				'veic_cod_munic' => $veic_cod_munic,
				'veic_munic' => $this->input->post('veic_munic'),
				'veic_uf' => $this->input->post('veic_uf'),
				'veic_nota_cnpj' => $veic_nota_cnpj,
				'veic_nota_uf' => $this->input->post('veic_nota_uf'),
				'veic_nota_numero_nota' => $veic_nota_numero_nota,
				'veic_nota_envelope' => $this->input->post('veic_nota_envelope'),
				'veic_nota_serie' => $this->input->post('veic_nota_serie'),
				'veic_nota_crv' => $this->input->post('veic_nota_crv'),
				'veic_nota_urt' => $this->input->post('veic_nota_urt'),
				'veic_nota_insc_estadual' => $veic_nota_insc_estadual,
				'veic_nota_data' => $veic_nota_data,
				'veic_nota_valor' => $veic_nota_valor,
				'veic_adicionais_obs_resumida' => $this->input->post('veic_adicionais_obs_resumida'),
				'veic_adicionais_exigencia' => $this->input->post('veic_adicionais_exigencia'),
				'veic_adicionais_acessorios_adicionais' => $this->input->post('veic_adicionais_acessorios_adicionais'),
				'veic_adicionais_nome_usuario' => $this->input->post('veic_adicionais_nome_usuario'),
				'veic_adicionais_email' => $this->input->post('veic_adicionais_email'),
				'veic_adicionais_ddd' => $this->input->post('veic_adicionais_ddd'),
				'veic_adicionais_usuario_telefone' => $this->input->post('veic_adicionais_usuario_telefone'),
				'veic_condutor_nome_condutor' => $this->input->post('veic_condutor_nome_condutor'),
				'veic_condutor_tel_1' => $this->input->post('veic_condutor_tel_1'),
				'veic_condutor_tel_2' => $this->input->post('veic_condutor_tel_2'),
				'veic_condutor_email' => $this->input->post('veic_condutor_email'),
				'veic_obs_livre' => $this->input->post('veic_obs_livre'),
            );

                $this->Veiculo_model->update_veiculo($veic_id,$params);

				$nome = $this->input->post('veic_codigo');
				$this->session->set_flashdata(array('msg' => 'atualizar' , 'nome' => $nome));
	
                redirect('veiculo/index');
            }
            else
            {   
                $data['veiculo'] = $this->Veiculo_model->get_veiculo($veic_id);
    
                $data['pagina'] = "Veículos";
                $data['sub_pagina'] = "Editar Veículos";
                $this->load->view('header_view',$data);
                $this->load->view('veiculo/editar',$data);
                $this->load->view('footer_view',$data);
            }
        }
        else
            show_error('The veiculo you are trying to editar does not exist.');
    } 

    /*
     * Deleting veiculo
     */
    function remove($veic_id)
    {
        $veiculo = $this->Veiculo_model->get_veiculo($veic_id);

        // check if the veiculo exists before trying to delete it
        if(isset($veiculo['veic_id']))
        {
            $this->Veiculo_model->delete_veiculo($veic_id);
            redirect('veiculo/index');
        }
        else
            show_error('The veiculo you are trying to delete does not exist.');
    }
    
}
