<?php
/* 
 * Generated by CRUDigniter v2.0 Beta 
 * www.crudigniter.com
 */
 
class Carroceria_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * get a carroceria by carrocerias_id
     */
    function get_carroceria($carrocerias_id)
    {
        return $this->db->get_where('carrocerias',array('carrocerias_id'=>$carrocerias_id))->row_array();
    }
    
    /*
     * get all carrocerias
     */
    function get_all_carrocerias()
    {
        return $this->db->get('carrocerias')->result_array();
    }
    
    /*
     * function to add new carroceria
     */
    function add_carroceria($params)
    {
        $this->db->insert('carrocerias',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update carroceria
     */
    function update_carroceria($carrocerias_id,$params)
    {
        $this->db->where('carrocerias_id',$carrocerias_id);
        $this->db->update('carrocerias',$params);
    }
    
    /*
     * function to delete carroceria
     */
    function delete_carroceria($carrocerias_id)
    {
        $this->db->delete('carrocerias',array('carrocerias_id'=>$carrocerias_id));
    }
}
