<?php
/* 
 * Generated by CRUDigniter v2.0 Beta 
 * www.crudigniter.com
 */
 
class Categoria_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * get a categoria by categorias_id
     */
    function get_categoria($categorias_id)
    {
        return $this->db->get_where('categorias',array('categorias_id'=>$categorias_id))->row_array();
    }
    
    /*
     * get all categorias
     */
    function get_all_categorias()
    {
        return $this->db->get('categorias')->result_array();
    }
    
    /*
     * function to add new categoria
     */
    function add_categoria($params)
    {
        $this->db->insert('categorias',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update categoria
     */
    function update_categoria($categorias_id,$params)
    {
        $this->db->where('categorias_id',$categorias_id);
        $this->db->update('categorias',$params);
    }
    
    /*
     * function to delete categoria
     */
    function delete_categoria($categorias_id)
    {
        $this->db->delete('categorias',array('categorias_id'=>$categorias_id));
    }
}
