<?php
/* 
 * Generated by CRUDigniter v2.0 Beta 
 * www.crudigniter.com
 */
 
class Combustivel_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * get a combustivei by combustiveis_id
     */
    function get_combustivel($combustiveis_id)
    {
        return $this->db->get_where('combustiveis',array('combustiveis_id'=>$combustiveis_id))->row_array();
    }
    
    /*
     * get all combustiveis
     */
    function get_all_combustiveis()
    {
        return $this->db->get('combustiveis')->result_array();
    }
    
    /*
     * function to add new combustivei
     */
    function add_combustivel($params)
    {
        $this->db->insert('combustiveis',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update combustivei
     */
    function update_combustivel($combustiveis_id,$params)
    {
        $this->db->where('combustiveis_id',$combustiveis_id);
        $this->db->update('combustiveis',$params);
    }
    
    /*
     * function to delete combustivei
     */
    function delete_combustivel($combustiveis_id)
    {
        $this->db->delete('combustiveis',array('combustiveis_id'=>$combustiveis_id));
    }
}
