<?php
/* 
 * Generated by CRUDigniter v2.0 Beta 
 * www.crudigniter.com
 */
 
class Cor_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * get a core by cores_id
     */
    function get_cor($cores_id)
    {
        return $this->db->get_where('cores',array('cores_id'=>$cores_id))->row_array();
    }
    
    /*
     * get all cores
     */
    function get_all_cores()
    {
        return $this->db->get('cores')->result_array();
    }
    
    /*
     * function to add new core
     */
    function add_cor($params)
    {
        $this->db->insert('cores',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update core
     */
    function update_cor($cores_id,$params)
    {
        $this->db->where('cores_id',$cores_id);
        $this->db->update('cores',$params);
    }
    
    /*
     * function to delete core
     */
    function delete_cor($cores_id)
    {
        $this->db->delete('cores',array('cores_id'=>$cores_id));
    }
}
