<?php
/* 
 * Generated by CRUDigniter v2.0 Beta 
 * www.crudigniter.com
 */
 
class Despachante_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * get a despachante by desp_id
     */
    function get_despachante($desp_id)
    {
        return $this->db->get_where('despachantes',array('desp_id'=>$desp_id))->row_array();
    }
    
    /*
     * get all despachantes
     */
    function get_all_despachantes()
    {
        return $this->db->get('despachantes')->result_array();
    }
    
    /*
     * function to add new despachante
     */
    function add_despachante($params)
    {
        $this->db->insert('despachantes',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update despachante
     */
    function update_despachante($desp_id,$params)
    {
        $this->db->where('desp_id',$desp_id);
        $this->db->update('despachantes',$params);
    }
    
    /*
     * function to delete despachante
     */
    function delete_despachante($desp_id)
    {
        $this->db->delete('despachantes',array('desp_id'=>$desp_id));
    }
}
