<?php
/* 
 * Generated by CRUDigniter v2.0 Beta 
 * www.crudigniter.com
 */
 
class Especie_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * get a especie by especies_id
     */
    function get_especie($especies_id)
    {
        return $this->db->get_where('especies',array('especies_id'=>$especies_id))->row_array();
    }
    
    /*
     * get all especies
     */
    function get_all_especies()
    {
        return $this->db->get('especies')->result_array();
    }
    
    /*
     * function to add new especie
     */
    function add_especie($params)
    {
        $this->db->insert('especies',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update especie
     */
    function update_especie($especies_id,$params)
    {
        $this->db->where('especies_id',$especies_id);
        $this->db->update('especies',$params);
    }
    
    /*
     * function to delete especie
     */
    function delete_especie($especies_id)
    {
        $this->db->delete('especies',array('especies_id'=>$especies_id));
    }
}
