<?php
/* 
 * Generated by CRUDigniter v2.0 Beta 
 * www.crudigniter.com
 */
 
class Marcas_modelo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * get a marcas_modelo by marcas_modelos_id
     */
    function get_marcas_modelo($marcas_modelos_id)
    {
        return $this->db->get_where('marcas_modelos',array('marcas_modelos_id'=>$marcas_modelos_id))->row_array();
    }
    
    /*
     * get all marcas_modelos
     */
    function get_all_marcas_modelos()
    {
        return $this->db->get('marcas_modelos')->result_array();
    }
    
    /*
     * function to add new marcas_modelo
     */
    function add_marcas_modelo($params)
    {
        $this->db->insert('marcas_modelos',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update marcas_modelo
     */
    function update_marcas_modelo($marcas_modelos_id,$params)
    {
        $this->db->where('marcas_modelos_id',$marcas_modelos_id);
        $this->db->update('marcas_modelos',$params);
    }
    
    /*
     * function to delete marcas_modelo
     */
    function delete_marcas_modelo($marcas_modelos_id)
    {
        $this->db->delete('marcas_modelos',array('marcas_modelos_id'=>$marcas_modelos_id));
    }
}
