<?php
/* 
 * Generated by CRUDigniter v2.0 Beta 
 * www.crudigniter.com
 */
 
class Restricao_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * get a restrico by restricoes_id
     */
    function get_restricao($restricoes_id)
    {
        return $this->db->get_where('restricoes',array('restricoes_id'=>$restricoes_id))->row_array();
    }
    
    /*
     * get all restricoes
     */
    function get_all_restricoes()
    {
        return $this->db->get('restricoes')->result_array();
    }
    
    /*
     * function to add new restrico
     */
    function add_restricao($params)
    {
        $this->db->insert('restricoes',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update restrico
     */
    function update_restricao($restricoes_id,$params)
    {
        $this->db->where('restricoes_id',$restricoes_id);
        $this->db->update('restricoes',$params);
    }
    
    /*
     * function to delete restrico
     */
    function delete_restricao($restricoes_id)
    {
        $this->db->delete('restricoes',array('restricoes_id'=>$restricoes_id));
    }
}
