<?php
/* 
 * Generated by CRUDigniter v2.0 Beta 
 * www.crudigniter.com
 */
 
class Tipo_veiculo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * get a tipo_veiculo by tipo_veiculos_id
     */
    function get_tipo_veiculo($tipo_veiculos_id)
    {
        return $this->db->get_where('tipo_veiculos',array('tipo_veiculos_id'=>$tipo_veiculos_id))->row_array();
    }
    
    /*
     * get all tipo_veiculos
     */
    function get_all_tipo_veiculos()
    {
        return $this->db->get('tipo_veiculos')->result_array();
    }
    
    /*
     * function to add new tipo_veiculo
     */
    function add_tipo_veiculo($params)
    {
        $this->db->insert('tipo_veiculos',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tipo_veiculo
     */
    function update_tipo_veiculo($tipo_veiculos_id,$params)
    {
        $this->db->where('tipo_veiculos_id',$tipo_veiculos_id);
        $this->db->update('tipo_veiculos',$params);
    }
    
    /*
     * function to delete tipo_veiculo
     */
    function delete_tipo_veiculo($tipo_veiculos_id)
    {
        $this->db->delete('tipo_veiculos',array('tipo_veiculos_id'=>$tipo_veiculos_id));
    }
}
