<?php
/* 
 * Generated by CRUDigniter v2.0 Beta 
 * www.crudigniter.com
 */
 
class Veiculo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * get a veiculo by veic_id
     */
    function get_veiculo($veic_id)
    {
        return $this->db->get_where('veiculos',array('veic_id'=>$veic_id))->row_array();
    }
    
    /*
     * get all veiculos
     */
    function get_all_veiculos()
    {
        return $this->db->get('veiculos')->result_array();
    }
    
    /*
     * function to add new veiculo
     */
    function add_veiculo($params)
    {
        $this->db->insert('veiculos',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update veiculo
     */
    function update_veiculo($veic_id,$params)
    {
        $this->db->where('veic_id',$veic_id);
        $this->db->update('veiculos',$params);
    }
    
    /*
     * function to delete veiculo
     */
    function delete_veiculo($veic_id)
    {
        $this->db->delete('veiculos',array('veic_id'=>$veic_id));
    }
}
